name: Node CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12]

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup (Node.js ${{ matrix.node-version }})
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: npm ci
    - name: Build
      run: |
        npm run init
        npm run prod
        # https://github.blog/2009-12-29-bypassing-jekyll-on-github-pages/
        touch dist/.nojekyll
        # https://help.github.com/en/articles/managing-a-custom-domain-for-your-github-pages-site
        echo btcpayserver.org > dist/CNAME
      env:
        CI: true
        TRANSIFEX_TOKEN: ${{ secrets.TRANSIFEX_TOKEN }}
    - name: Deploy
      if: success()
      uses: maxheld83/ghpages@v0.2.1
      env:
        BUILD_DIR: dist/
        GH_PAT: ${{ secrets.GH_PAT }}
